package bg.softuni.hrm_users.model.enums;

public enum DepartmentName {
    EXECUTIVES,
    FINANCE_DEPARTMENT,
    HR_DEPARTMENT,
    ADMINISTRATIVE_DEPARTMENT,
    PROJECT_MANAGEMENT_DEPARTMENT,
    MARKETING_DEPARTMENT,
    IT_DEPARTMENT,
    CUSTOMER_SUPPORT_DEPARTMENT,
    MAINTENANCE_DEPARTMENT,
    DEFAULT_DEPARTMENT
}
